version: '3.7'
services:
  agent_monitor:
    image: douglasrcampos/agent-monitor:1.3
    ports:
      - "8080:8080"
    depends_on:
      - postgres_rnp
    networks:
      - dev

  postgres_rnp:
    build:
      context: ./postgres
    image: douglasrcampos/postgres_rnp:latest
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    networks:
      - dev


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Persistência de dados do Grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin     # Usuário padrão
      GF_SECURITY_ADMIN_PASSWORD: admin # Senha padrão
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  grafana_data:  # Volume para persistir dashboards e configurações